---
services:
  db:
    image: poornapj/pythonproject:dbimage
    ports:
      - "3306:3306"
   


  auth_service:
    image: poornapj/pythonproject:authimage
    ports:
      - "5001"
    


  book_service:
    image: poornapj/pythonproject:bookimage
    ports:
      - "5002"
    


  borrow_service:
    image: poornapj/pythonproject:borrowimage
    ports:
      - "5003"
    

  templates:
    image: poornapj/pythonproject:templateimage
    ports:
      - "5000"
    
